name: CI - Build WinForms Project

on:
  push:
    branches:
      - master
      - develop
      - feature/github-actions

  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restaurar paquetes NuGet
        run: nuget restore DataFlowManager.sln

      - name: Compilar solucion
        run: msbuild DataFlowManager.sln /p:Configuration=Release /p:Platform="Any CPU"
